### ISSUE TITLE
Token not supported on windows

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes-sigs/sig-windows-dev-tools#114]
## What I did

- Set up cluster via `make 2-vagrant-up`
- Modified the iis configuration to use new image per https://github.com/kubernetes-sigs/sig-windows-dev-tools/issues/86#issuecomment-912991747 Then modified the command as needed.
- Try `sonobuoy run --mode=quick` but the container never gets created
- 
## What I see

```
# kubectl get events -n sonobuoy
LAST SEEN   TYPE      REASON        OBJECT         MESSAGE
14m         Normal    Scheduled     pod/sonobuoy   Successfully assigned sonobuoy/sonobuoy to winw1
14m         Warning   FailedMount   pod/sonobuoy   MountVolume.SetUp failed for volume "kube-api-access-vjdzc" : chown c:\var\lib\kubelet\pods\030d385f-0170-497d-88c9-7648ac605b0d\volumes\kubernetes.io~projected\kube-api-access-vjdzc\..2021_09_30_19_16_32.666241218\token: not supported by windows
```

**Comment by johnSchnake** [comment]
This is from the service account and I wasn't aware anything related to those would be windows dependent. Looking into it...

**Comment by johnSchnake** [comment]
Found this in the kubelet logs:

```
E0930 12:48:20.762673    4764 atomic_writer.go:404] pod sonobuoy/sonobuoy volume kube-api-access-z2n54: unable to change file c:\var\lib\kubelet\pods\f6cb1213-116b-412a-a495-ca79b0a0837a\volumes\kubernetes.io~projected\kube-api-access-z2n54\..2021_09_30_
19_48_20.822340194\token with owner 1000: chown c:\var\lib\kubelet\pods\f6cb1213-116b-412a-a495-ca79b0a0837a\volumes\kubernetes.io~projected\kube-api-access-z2n54\..2021_09_30_19_48_20.822340194\token: not supported by windows
```
So it is probably a `chown` command, not the token that isn't supported by windows.

This would potentially be related to a Sonobuoy change lately where we specified the user/group for the pod. Seems odd but that may not be supported by Windows? TBD. Will follow up after I remove that and see if it works.

**Comment by jsturtevant** [comment]
this looks to be https://github.com/kubernetes/kubernetes/issues/102849

**Comment by johnSchnake** [comment]
Closing since it seems to be an upstream issue and not this config. Removed that security context and I was able to get things running just fine. Though FWIW I hit another api/permission issue I've got to debug:

```
time="2021-09-30T12:57:02-07:00" level=error msg="could not get api group resources: Get \"https://10.96.0.1:443/api?timeout=32s\": dial tcp 10.96.0.1:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond."
```
