### ISSUE TITLE
Host-process containers research

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/sig-windows-dev-tools#123]
Lets document in our `experiments/` section

- can look at the code here https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/1672 
- run host-process  kube-proxy 
- run host-process calico 
- run host-process antrea 

From there in a follow on issue we can implement it in automation...

**Comment by lippertmarkus** [comment]
For anyone coming across this issue and want to try HostProcess right away: https://github.com/kubernetes-sigs/sig-windows-dev-tools/issues/110#issuecomment-960558105
