### ISSUE TITLE
error during make kubernetes step

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/sig-windows-dev-tools#129]
@NikhilSharmaWe Can you add details here?

**Comment by NikhilSharmaWe** [comment]
@jayunit100 I am trying to make a local kubernetes cluster for testing the changes I make in the repo.

- I followed the steps mentioned in [Quick start](Quick start) in Readme of sig-windows-dev-tools. But when I run make all comamand I get this error `Makefile:1: *** missing separator .   Stop.`

But when I tried it to run at present the process was stuck on Building Docker image step, as you can see in the image.
![Screenshot (664)](https://user-images.githubusercontent.com/77074571/145088989-ead41bd8-9a70-4f1e-a2d9-185553952e71.png)

- These are the details of my system.
![Screenshot (663)](https://user-images.githubusercontent.com/77074571/145089209-14b243b8-fa05-4fd3-89d0-4be72203ce1f.png)

**Comment by NikhilSharmaWe** [comment]
@jayunit100 I am trying to make a local kubernetes cluster for testing the changes I make in the repo.

- I followed the steps mentioned in [Quick start](Quick start) in Readme of sig-windows-dev-tools. But when I run make all comamand I get this error `Makefile:1: *** missing separator .   Stop.`

But when I tried it to run at present the process was stuck on Building Docker image step, as you can see in the image.
![Screenshot (664)](https://user-images.githubusercontent.com/77074571/145088989-ead41bd8-9a70-4f1e-a2d9-185553952e71.png)

- These are the specifications of my system.

**Device Specifications**

Device name    	DESKTOP-ISNGT7P
Processor        	Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz   2.71 GHz
Installed RAM	        8.00 GB (7.88 GB usable)
System type	        64-bit operating system, x64-based processor

**Windows Specifications**

Edition	                Windows 10 Pro
Version	                21H1
OS build	               19043.1348
Experience	        Windows Feature Experience Pack 120.2212.3920.0

**Comment by jayunit100** [comment]
Hmmm it just hangs?

**Comment by NikhilSharmaWe** [comment]
I let it run for over 30 minutes and then I stopped it by ctrlC because there was no change, I thought something was wrong.
