### ISSUE TITLE
Document variables file in sync/shared in README.md

### ISSUE THREAD

**Issue by dougsland** [kubernetes-sigs/sig-windows-dev-tools#149]
# Question: What's the reason to have two variables file?
```
$ ls sync/shared/va*
sync/shared/variables-lite.yaml 
sync/shared/variables.yaml
```

# Question: What's the meaning for each entry in the file?
```
# cat variables.yaml | grep ": " | egrep -v ^\#
kubernetes_sha: "286709307da5adb62e78d989b7ed846355d5c88e"
kubernetes_compatibility:  "1.21.2"
overwrite_windows_bins: "false"
kubelet_path:  "./sync/windows/bin/kubelet.exe"
kubeproxy_path:  "./sync/windows/bin/kube-proxy.exe"
windows_node_ip: "10.20.30.11"
k8s_linux_registry: "gcr.io/k8s-staging-ci-images"
k8s_linux_kubelet_deb:  "1.21.0"
k8s_linux_apiserver: "ci/v1.22.0-alpha.3.31+a3abd06ad53b2f"
k8s_linux_kubelet_nodeip: "10.20.30.10"
overwrite_linux_bins: false
linux_ram: 4096
linux_cpus: 4
windows_ram: 6048
windows_cpus: 4
cni: "antrea"
```
# Question: Why the `variables-lite.yaml` contain different number of entries from `variables.yaml`? 

- For example:

`16 entries in variables.yaml` 
 ```
       # cat variables.yaml | grep ": " | egrep -v ^\# | wc -l
      16
 ```

`13 entries in variables-lite.yaml` 
 ``` 
      # cat variables-lite.yaml | grep ": " | egrep -v ^\# | wc -l
      13
```

# Question: Is variables-lite.yaml working at all? 
```

```

# Question: Can we have reduced number of entries ? Which values it will assume?
```

```

See-also: https://github.com/kubernetes-sigs/sig-windows-dev-tools/pull/148

**Comment by dougsland** [comment]
@knabben @aravindhp could you please add tag `good-for-first-issue?` I don't have perms.

**Comment by aravindhp** [comment]
@dougsland looks that label is not available

**Comment by dougsland** [comment]
@aravindhp looks like it's a different command, thanks anyway :) teamwork++
