### ISSUE TITLE
make CNI_NAME target

### ISSUE THREAD

**Issue by dougsland** [kubernetes-sigs/sig-windows-dev-tools#156]
Would be nice to have `calico` and `antrea` or others CNI as target so easy to clone and deploy a working environment with your favourite CNI.

Example:
`#  make calico` will execute behind the scenes in the makefile:

```
calico:
     @sed -i 's/cni:.*/cni: "calico"/g' sync/shared/variables.yaml
     $(MAKE) -e 2 (or all or the target that trigger the build of the project)
```

The same apply to the others CNI supported by the project.

**Comment by jayunit100** [comment]
spoke w/ doug and amim - we can make a large MR to fix this in side of #177
