### ISSUE TITLE
[ERROR FileAvailable-C:-etc-kubernetes-pki-ca.crt]: C:/etc/kubernetes/pki/ca.crt already exists

### ISSUE THREAD

**Issue by dougsland** [kubernetes-sigs/sig-windows-dev-tools#168]
```
$ git clone https://github.com/kubernetes-sigs/sig-windows-dev-tools.git && cd  sig-windows-dev-tools
$ sig-windows-dev-tools> make
```

^C==> winw1: Waiting for cleanup before exiting...
    winw1: [preflight] Running pre-flight checks
    winw1: W0118 18:06:11.658689    1072 checks.go:1022] [preflight] WARNING: Couldn't create the interface used for talking to the container runtime: crictl is required by the container runtime: exec: "crictl": executable file not found in %PATH%
    winw1: error execution phase preflight: [preflight] Some fatal errors occurred:
    winw1: 	[ERROR FileAvailable-C:-etc-kubernetes-pki-ca.crt]: C:/etc/kubernetes/pki/ca.crt already exists
    winw1: [preflight] If you know what you are doing, you can make a check non-fatal with `--ignore-preflight-errors=...`
    winw1: To see the stack trace of this error execute with --v=5 or higher
Vagrant exited after cleanup due to external interrupt.

**Comment by knabben** [comment]
```
winw1: [ERROR FileAvailable-C:-etc-kubernetes-pki-ca.crt]: C:/etc/kubernetes/pki/ca.crt already exists
```

we do not support rerun, looks like the node was already joined and fail, adding `vagrant destroy` on make to decrease this kind of issues.

/close
