### ISSUE TITLE
avoid git clone kubernetes everytime `make all` is executed

### ISSUE THREAD

**Issue by dougsland** [kubernetes-sigs/sig-windows-dev-tools#172]
`make all` has the target `make clean` to make sure the environment is clean before building the sig-widows-dev-tools environment.

This is a great but enforce developers to `git clone kubernetes` tree every time a new test need to be executed. This consume time when downloading hundreds of MB, bandwidth and time rebuilding kubernetes.   For now, I would just remove `make clean` as requirement for `make all`

**Comment by jayunit100** [comment]
moved here https://github.com/kubernetes-sigs/sig-windows-dev-tools/issues/177
