### ISSUE TITLE
Stupid question: What environment is expected for executing "make all"?

### ISSUE THREAD

**Issue by carkrueger** [kubernetes-sigs/sig-windows-dev-tools#186]
Hi,

what environment is expected for executing "make all"?

-Cygwin?
-msys2?
-WSL?

greetings
Carsten

**Comment by knabben** [comment]
hi Carsten

this is being tested only on Linux (mostly tested on ubuntu machines) due to vagrant compatibility in these other env.

**Comment by dougsland** [comment]
@knabben already addressed the question. Closing for now.
See Also: https://github.com/kubernetes-sigs/sig-windows-dev-tools/issues/203
