### ISSUE TITLE
OpenSSL installer link is now broken in 0-antrea.ps1

### ISSUE THREAD

**Issue by luckerby** [kubernetes-sigs/sig-windows-dev-tools#188]
Trying to setup the 2-node setup never completes, as the Windows nodes runs into a problem when running the 0-antrea.ps1 script as seen in the [full log here](https://gist.github.com/luckerby/b2dc0dc908bddb81a933909abcb6ce73). On a closer look, downloading the OpenSSL client yields a strange 153-bytes executable. The reason for this is the respective version no longer exists on the source site that provides the OpenSSL Windows binary.

**Comment by dougsland** [comment]
This issue has being resolved by the patch below. Feel free to re-open in case it still shows up.

```
commit 845d44ae9adf66568b3f3f369010c64b41032599
Author: jay vyas <jvyas@vmware.com>
Date:   Sun Jun 5 12:17:59 2022 -0400

    Add antrea ssl file
```
