### ISSUE TITLE
Cannot schedule pods on the Windows node

### ISSUE THREAD

**Issue by luckerby** [kubernetes-sigs/sig-windows-dev-tools#189]
After completing the setup for the 2 nodes-setup (1x Linux control plane node and 1x Windows worker node), and ensuring that the configuration is finished on both nodes (due to #188 this currently means pasting the 1-antrea.ps1 file in an SSH connection on the Windows node (the file cannot be accessed by going to C:\sync\windows) for whatever reason)) trying to schedule a pod on the Windows node doesn't work as expected:

```
  Warning  FailedCreatePodSandBox  22s (x105 over 23m)  kubelet  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "9125a4d13f634963a8f635f987c5be41d826fb5f9400ff2aa80706db6a929da5": rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing open \\\\.\\pipe\\cnisock: The system cannot find the file specified."
```

There is an issue opened on the antrea repo [here](https://github.com/antrea-io/antrea/issues/1581) - currently closed due to inactivity - which further leads to [this issue](https://github.com/containerd/containerd/issues/4851) on the containerd repo. As the discussion in the latter doesn't seem to suggest any fix coming soon, is there any workaround for now?

**Comment by knabben** [comment]
For this issue in particular it's related with the missing OpenSSL installation
https://github.com/kubernetes-sigs/sig-windows-dev-tools/issues/188

**Comment by dougsland** [comment]
As @knabben mentioned, related to #188. Closing as dup
