### ISSUE TITLE
True Windows Support

### ISSUE THREAD

**Issue by luthermonson** [kubernetes-sigs/sig-windows-dev-tools#203]
The solution for windows support is to run everything in WSL since there is no real support for `make` on windows. This is functional but everything in this repo can be ran in windows with no issues if we do one of the following two things...

1. There really isn't any great support for Makefile on windows and it's best to avoid if you want a cross platform tool. My personal favorite way to fix this problem is to use [Mage](https://magefile.org/). This way you're doing everything in go and people can install mage and use it cross platform on their own.
2. We could migrate from a Makefile to a go cli and put all the functionality in there. Since this is a tool to boot kube clusters in vagrant it might make the most sense since it's more likely you'll be working in a branch of kube and it doesn't make sense to change dir over to this repo to run `make` commands to test your changes.

I'm open to both implementations if someone wants to make a decision on which direction we should take.

**Comment by mloskot** [comment]
I found this issue while learning the actual host environment requirements, see #244
Would it be possible to resurrect this idea?

**Comment by mloskot** [comment]
I submitted a PowerShell-based prototype in #254 
The Mage, or a driver written in Go in general, is still a compelling idea to me and I'd like to work on it as soon the cluster setup is in shape and runnable with the simple script.

**Comment by knabben** [comment]
+1 for aiming in Made in the long run

**Comment by knabben** [comment]
The solution uses Powershell-script for now, what can fulfill the requirement of the issue. Closing as soon #254 is merged.

**Comment by mloskot** [comment]
@knabben & @luthermonson 
> +1 for aiming in Made in the long run

I've just proposed Magefiles for Mage in
- #259

**Comment by mloskot** [comment]
I think this can be closed as replaced by the currently ongoing SWDT CLI sub-project
- #278 (see #277 for context)
