### ISSUE TITLE
add a "test.sh" script

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/sig-windows-dev-tools#207]
since we dont have CI lets do this.

1) Add a test.sh script to the repo
2) When we make PRs , people run the test.sh script.
3) The script  takes as input (CNI, k8s commit ID). 
- runs make all... makes a new cluster from k8s master w calico or antrea (option) 
- Runs operational readiness spec w/ Core test specification 
- Passes or Fails based on results

This can be broken into two issues. 

- First we make the test.sh script
- Then, we add the Operational Readiness spec tests

Once it works, locally, w vbox, it can be standard protocol to run it for new commits. 

Then, eventually we can use this as the basis for #206

**Comment by dougsland** [comment]
@jayunit100 we have VT-x limitation describe in #206 please let me know your thoughts.
