### ISSUE TITLE
break out instructions for different OS's getting started guides... and add ubuntu partitioning windows directions for windows users

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/sig-windows-dev-tools#219]
we never gave windows users an option , and we want to 
provide QeMU eventually, but for now, 

1) lets start w/ a 
*windows.md* file 
file that has instructions to 
- partition a win machine to support ubuntu
- setup ubuntu w/ virtualbox and vagrant
- run make all as normal 

2) break out the ubuntu directions into an *ubuntu.md* file

**Comment by mloskot** [comment]
I think we're close to make the workflow OS agnostic with unified CLI based on Magefiles. So, the goal being there should be no need to for OS-specific instructions thus this can be closed indeed.
