### ISSUE TITLE
README_QEMU.md initial stub doc

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/sig-windows-dev-tools#220]
lets see if we can find a way to use 

- QEMU on mac to 

STart an ubuntu VM
Start a windows VM

If we can do that, we have an initial recipe that can be automated
later on in vagrant.

**Comment by aravindhp** [comment]
Given libvirt [works](https://github.com/kubernetes-sigs/sig-windows-dev-tools/issues/157#issuecomment-1342892794) on all platforms, I suggest we use libvirt given that will allow use of `kvm` on Linux and better performance.

**Comment by jayunit100** [comment]
As a first pass to experiment you can: 
- [ ] ubuntu VM w/ qemu on mac
- [ ]  windows iso VM w/ qemu mac
- [ ] ping windows vm from mac from your QEMU linux VM
- [ ] install kubeadm w/ linux on the linux VM 
- [ ] install kubeadm w/ windows, on the windows vm 
Then, if we can commit a "README_QEMU.md" as a first pass, and then to finish this issue, lets

But the really useful thing is: 

- [ ] swap out the vagrant QEMU provider with `controlplane.vm.provider :qemu do |vb|`

**Comment by gpramita** [comment]
Ok looking into it.

**Comment by pramitagautam** [comment]
We filed this issue https://github.com/ppggff/vagrant-qemu/issues/32.
The progress can be tracked on this bug.
