### ISSUE TITLE
Vagrant AWS Provider

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/sig-windows-dev-tools#225]
QEMU didnt work out quite the way we wanted to but we'll reach out to the developers to figure it out in the future.

Lets file our experiment results in the README, and then
lets make an AWS provider recipe that folks can use.

... ( We filed https://github.com/ppggff/vagrant-qemu/issues/32 so , at some point,
we can get back to the goal of a completely free and easy to use QEMU 
recipe for windows k8s development that can run on any laptop... but for now, vbox and AWS will have to suffice !)

**Comment by pramitagautam** [comment]
Ok, so the https://github.com/mitchellh/vagrant-aws for sig tools didnt work as it has been deprecated.
I am going to work on terraform on AWS.
So closing this issue.
