### ISSUE TITLE
typo: trigera

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/sig-windows-dev-tools#239]
we misspelled "trigera" .  anyone wanting to contribute, easy fix :) 
it should be `tigera`.  

after fixing it please run `make all` and confirm that the calico CNI comes up properly (you need virtualbox , vagrant, installed, and an amd64 mac or linux machine)

/good-first-issue

**Comment by Shivraj-Nakum** [comment]
@jayunit100  where do have to make changes ?
