### ISSUE TITLE
figure out miscellaneous issues on master-qemu  m1 Macs/

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/sig-windows-dev-tools#240]
We need to finish getting the branch, master-qemu tested on linux and Mac m1/m2 machines.

Other users can continue w/ the virtual box recipes.  
 
To do this, 
- we need to figure out why we can't write to the /tmp directory
```
If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
failed_win_up
cni: calico
qemu loopcalico: 3.25.0; containerd: 1.6.15
==> winw1: Running provisioner: shell...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mkdir -p "/tmp"

Stdout from the command:
```

**Comment by mloskot** [comment]
I think this can be closed as replaced by the currently ongoing SWDT CLI sub-project
- #278 (see #277 for context)
- VirtualBox-based setup is being replaced
