### ISSUE TITLE
Could you enable Discussions for this repository?

### ISSUE THREAD

**Issue by mloskot** [kubernetes-sigs/sig-windows-dev-tools#247]
Although there is `#sig-windows` channel on https://slack.k8s.io suitable for real-time or ad-hoc communication, I think it would be helpful to add Discussions forum to this repository for longer topics which do not fit the category of Issues.

Additionally, it would be very helpful to have such discussions archived here for search and reference to other users.

For example, I think most of my notes I posted as comments to https://github.com/kubernetes-sigs/sig-windows-dev-tools/pull/245 would better fit a discussion thread, rather than docs-specific PR.

**Comment by jayunit100** [comment]
Can you help us with that mloskot ? maybe asking in the contrib-x slack channel ?

**Comment by mloskot** [comment]
@jayunit100 I've forwarded my call to `#sig-contribex`, see https://kubernetes.slack.com/archives/C1TU9EB9S/p1681745267367819

**Comment by jayunit100** [comment]
Thank you sir !!! Just ping us if you need approvals on anything

**Comment by mloskot** [comment]
The feedback via Slack has been this:
- There is already number of comm channels Slack, discuss.k8s.io, GitHub issues and mailing list
- Any discussion space should not be left on its own but rather moderated/maintained, and there are no resources to provide that

I'm closing this issue for now.

Thank you @jayunit100 @riverar @BenTheElder @jberkus

**Comment by jayunit100** [comment]
ok lets just use discuss.k8s.io for questions that we want to maintain the conversation around as a discussion? sgtm
