### ISSUE TITLE
replace make w/ a powershell script that is cross platform

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/sig-windows-dev-tools#252]
windows doesnt support make and now that we have https://github.com/mloskot/sig-windows-dev-tools/blob/ml/make-with-powershell/Makefile.ps1 as a prototype, a simple executable ps1 will be more expressive and will support the important task of fully supporting a windows laptop development workflow !

**Comment by jayunit100** [comment]
closing, as matesuz will file this when ready.

**Comment by mloskot** [comment]
Done in #254
