### ISSUE TITLE
test vagrant recipes on windows !

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/sig-windows-dev-tools#5]
@phillipsj

**Comment by phillipsj** [comment]
@jayunit100 @FriedrichWilken so the current version of Vagrant has an issue on Windows. I have tried the work around and it still doesn't work. I will try downgrading and see what happens. 

https://github.com/hashicorp/vagrant/issues/12121

**Comment by FriedrichWilken** [comment]
I have started to work on this [in this fork](https://github.com/FriedrichWilken/sig-windows-dev-tools). For now I have created a second Vagrantfile. I hope we can later consolidate the vagrantfiles.
