### ISSUE TITLE
Enable SSH on Windows nodes

### ISSUE THREAD

**Issue by marosset** [kubernetes-sigs/sig-windows-dev-tools#60]
We should enable SSH on the Windows nodes (because who likes using WinRM...)

Here is some powershell we use in aks-engine to start the ssh server and add authorized keys.
https://github.com/Azure/aks-engine/blob/master/parts/k8s/windowsinstallopensshfunc.ps1

**Comment by perithompson** [comment]
this is completed by #66 think this can be closed
