### ISSUE TITLE
container runtime not honored, lets remove it from kubelet startup on windows

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/sig-windows-dev-tools#74]
in the windows kubelet startup, we try to specify the pause image, but theres no reason to do this: 

```
--pod-infra-container-image=`"mcr.microsoft.com/oss/kubernetes/pause:1.4.1`" 
--enable-debugging-handlers 
--cgroups-per-qos=false 
--enforce-node-allocatable=`"`" 
--network-plugin=cni 
--resolv-conf=`"`" 
--log-dir=/var/log/kubelet 
--logtostderr=false 
--image-pull-progress-deadline=20m 
--container-runtime=remote 
--container-runtime-endpoint=npipe:////.//pipe//containerd-containerd"
```

# Details on why this is a silly thing to do 

... But the kubelet itself, if 
```
--container-runtime=remote
```, doesn't actually honor that flag, will not actually use this option 

hence we actually only use 1.4.0 in ouur current containerd configs, are the ones that get used.
```
$config = Get-Content "$global:ConainterDPath\config.toml"
$config = $config -replace "bin_dir = (.)*$", "bin_dir = `"c:/opt/cni/bin`""
$config = $config -replace "conf_dir = (.)*$", "conf_dir = `"c:/etc/cni/net.d`""
$config | Set-Content "$global:ConainterDPath\config.toml" -Force 
```

So, i guess this is a longwinded way of saying lets not use the `--pod-infra-container-image` flag at all :) . 

i.e. in a running cluster, our windows node has this in the config.toml:
```
    sandbox_image = "mcr.microsoft.com/oss/kubernetes/pause:1.4.0"
```
hence theres a mismatch that could be confusing for folks long term


this is a minor issue but figured it was worth noting in detail in case people search for it

**Comment by perithompson** [comment]
@dims was saying this was needed yesterday?

**Comment by jsturtevant** [comment]
It was added to linux in image builder because it was missing: https://github.com/kubernetes-sigs/image-builder/issues/486
