### ISSUE TITLE
Move to Server Core 2019

### ISSUE THREAD

**Issue by perithompson** [kubernetes-sigs/sig-windows-dev-tools#78]
We should create a base image with hyperv (disabled hypervisor) and containers already setup on server core and vim installed as default for text editing to make the box as fast and small as possible

/kind feature

**Comment by FriedrichWilken** [comment]
Yes, I am already trying to get into this. Vim is a very valid point that I will add to my list.

**Comment by marosset** [comment]
I suggested we make our own images too on slack :)

**Comment by marosset** [comment]
https://github.com/kubernetes-sigs/sig-windows-dev-tools/issues/57

**Comment by perithompson** [comment]
We could use imagebuilder but it changes the logic a little to replacing things that are already there rather than installing fresh,  did we ever find out if we can use GH actions to run a vagrant build?
