### ISSUE TITLE
Faster iteration via preloading Windows images

### ISSUE THREAD

**Issue by johnSchnake** [kubernetes-sigs/sig-windows-dev-tools#98]
Pulling the windows images often takes a long time, slowing down iteration time.

We should establish a way to prepull the images locally on the host and then move/load them into the Windows machine.

Since you cant do something like `docker pull...` for windows images when you're on mac/linux, we need to download them as tarballs and once the Windows machine comes up, load that tarball of images.

**Comment by knabben** [comment]
@johnSchnake what images are you using? maybe we can import the most used ones

**Comment by johnSchnake** [comment]
Just the main IIS one would even be a win; thats 17m:
```
17m         Normal    Pulling                   pod/windows-server-iis-769d57f976-c746j    Pulling image "mcr.microsoft.com/windows/servercore:1809"
4s          Normal    Pulled                    pod/windows-server-iis-769d57f976-c746j    Successfully pulled image "mcr.microsoft.com/windows/servercore:1809" in 17m27.0527779s
```

**Comment by claudiubelu** [comment]
I don't think your usecase is for E2E tests, but just FYI, we do have an option in E2E to prepull images on the nodes since we merged this: https://github.com/kubernetes/kubernetes/pull/105481 And we've been using it in the master test jobs as well.

One idea would be to do something similar: have a daemonset yaml with various images that should be pulled on the nodes. Maybe it's not ideal, but it's something that could work with what we currently have.

**Comment by johnSchnake** [comment]
So I haven't touched this in a while but wanted to make something clear for any other readers. I'm not just talking about pre-pulling the images before tests. I think thats what the above k8s functionality allows.

What I mean is that the Windows images are so large, pulling them from 'the wild' takes too long. As a result, if I have copies (e.g. in a tarball) on my local machine, and my images are on my local machine, I'd like to be able to just load them into the windows cluster avoiding all the extra network traffic.

So the first time you ever do it, yes you have to download the windows image tarballs. But for every iteration after that (cluster up/down/up/down/etc) then it just loads from from the local host avoiding a big download/pull.
