### ISSUE TITLE
image-builder-sandbox

### ISSUE THREAD

**Issue by jayunit100** [kubernetes-sigs/sig-windows-dev-tools#99]
Taking from https://github.com/kubernetes-sigs/sig-windows-tools/issues/169

```
make windows-server-image
-> call runme.sh
```
...  with all the docs for what we do with image builder for windows .... 

```

image-builder/
   runme.sh
   README.md
   cloud.json
   extraArgs.json
   roles/
       cni/
       csi/
       ...    
   ...
```

**Comment by FriedrichWilken** [comment]
how do we handle VagrantUp.com? Do we create a shared account there?
